services:
  portfolio:
    build:
      context: .
      args:
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
    image: integriq-profile
    container_name: integriq-profile
    ports:
      - "3333:3333"
    restart: unless-stopped
